//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS888.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.HoiDaps = new HashSet<HoiDap>();
        }
    
        public Nullable<int> MaLoaiSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<int> PhongTam { get; set; }
        public Nullable<int> PhongNgu { get; set; }
        public Nullable<bool> Sightseeing { get; set; }
        public string Direction { get; set; }
        public Nullable<System.DateTime> NgayXayDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> MaKTS { get; set; }
        public int MaSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoiDap> HoiDaps { get; set; }
        public virtual KienTrucSu KienTrucSu { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
